#!/bin/bash
set -uo pipefail

# Transfer Syntax Compatibility Test
#
# The synthetic data generator (scripts/generate-test-data.sh) emits every
# instance as Explicit VR Little Endian (UID 1.2.840.10008.1.2.1) only. This
# script exercises the *other* uncompressed transfer syntaxes that DCMTK's
# default storescp/dcmqrscp build accepts, so we have an automated signal
# when:
#   - `dcmconv` cannot perform the requested conversion (codec missing),
#   - the output file's (0002,0010) TransferSyntaxUID does not match the
#     requested target,
#   - `storescu` (the SCU) cannot negotiate the resulting transfer syntax
#     against the PACS SCP.
#
# Scope (intentionally minimal):
#   - Implicit VR Little Endian      (1.2.840.10008.1.2)
#   - Explicit VR Little Endian      (1.2.840.10008.1.2.1)  — round-trip
#   - Explicit VR Big Endian         (1.2.840.10008.1.2.2)  — retired in 2006
#                                                              but still in
#                                                              DCMTK's default
#                                                              transfer-syntax
#                                                              registry.
#
# No compressed transfer syntaxes (JPEG / JPEG-LS / RLE / JPEG2000) are
# exercised here: those require codec libraries (libjpeg, libcharls, ...)
# that are not part of the Debian `dcmtk` package this image installs.
# When/if a codec image variant is published, add the matching `dcmconv`
# flags (`+ej`, `+ee`, `+er`, ...) below.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/test-helpers.sh"

# ── Configuration ─────────────────────────────────────
PACS_HOST="${PACS_HOST:-pacs-server}"
PACS_PORT="${PACS_PORT:-11112}"
PACS_AE="${PACS_AE_TITLE:-DCMTK_PACS}"
MY_AE="${AE_TITLE:-TEST_SCU}"
TEST_DATA_DIR="${TEST_DATA_DIR:-/dicom/testdata}"

# Uncompressed transfer syntaxes always available with the DCMTK Debian
# package. Keep this list narrow on purpose; the README documents how to
# extend it once codec-enabled images ship.
TS_UID_IMPLICIT_LE="1.2.840.10008.1.2"
TS_UID_EXPLICIT_LE="1.2.840.10008.1.2.1"
TS_UID_EXPLICIT_BE="1.2.840.10008.1.2.2"

print_header "Transfer Syntax Compatibility Tests"

# ── Preamble: SCP reachable ──────────────────────────
ensure_scp_reachable "primary PACS" "${PACS_HOST}" "${PACS_PORT}" "${PACS_AE}" "${MY_AE}" || exit 1

# ── Locate a source instance ──────────────────────────
# The CT pool is generated by default. Fall back to any modality if CT is
# absent (e.g. someone disabled the CT branch in generate-test-data.sh).
SOURCE_FILE=$(find "${TEST_DATA_DIR}/ct" -name '*.dcm' 2>/dev/null | head -1)
if [ -z "${SOURCE_FILE}" ]; then
    SOURCE_FILE=$(find "${TEST_DATA_DIR}" -name '*.dcm' 2>/dev/null | head -1)
fi
if [ -z "${SOURCE_FILE}" ]; then
    print_fail "Transfer Syntax: no source .dcm file in ${TEST_DATA_DIR}"
    print_summary "Transfer Syntax"
    exit 1
fi

echo "  Source instance: ${SOURCE_FILE}"
echo ""

# ── Workspace ─────────────────────────────────────────
WORKDIR=$(mktemp -d -t transfer-syntax-XXXXXX)
# shellcheck disable=SC2064
trap "rm -rf '${WORKDIR}'" EXIT

# ── Helper: assert (0002,0010) matches an expected UID ─
assert_transfer_syntax_uid() {
    local label="$1"
    local file="$2"
    local expected_uid="$3"

    TEST_TOTAL=$((TEST_TOTAL + 1))

    local dump got_uid
    dump=$(dcmdump --search 0002,0010 --print-all "${file}" 2>/dev/null) || {
        print_fail "Transfer Syntax: ${label} dcmdump failed (${file})"
        TEST_FAILED=$((TEST_FAILED + 1))
        return 1
    }
    # dcmdump prints: (0002,0010) UI =LittleEndianExplicit  # 20, 1 TransferSyntaxUID
    # or the raw UID inside square brackets. Match either form.
    got_uid=$(echo "${dump}" | grep -m1 '(0002,0010)' \
        | sed -nE 's/.*\[([0-9.]+)\].*/\1/p')

    if [ -z "${got_uid}" ]; then
        # Fall back to the symbolic-name form (=LittleEndianImplicit etc.)
        # and resolve it via a small lookup table.
        local sym
        sym=$(echo "${dump}" | grep -m1 '(0002,0010)' \
            | sed -nE 's/.*=([A-Za-z0-9._]+).*/\1/p')
        case "${sym}" in
            LittleEndianImplicit) got_uid="${TS_UID_IMPLICIT_LE}" ;;
            LittleEndianExplicit) got_uid="${TS_UID_EXPLICIT_LE}" ;;
            BigEndianExplicit)    got_uid="${TS_UID_EXPLICIT_BE}" ;;
        esac
    fi

    if [ "${got_uid}" = "${expected_uid}" ]; then
        print_pass "Transfer Syntax: ${label} (0002,0010)=${got_uid}"
        TEST_PASSED=$((TEST_PASSED + 1))
        return 0
    fi

    print_fail "Transfer Syntax: ${label} expected (0002,0010)=${expected_uid} got=${got_uid:-<empty>}"
    TEST_FAILED=$((TEST_FAILED + 1))
    return 1
}

# ── Helper: dcmconv conversion ───────────────────────
# Args: LABEL FLAG IN OUT
# FLAG is the dcmconv output transfer syntax option (e.g. "+te", "+ti", "+tb").
convert_transfer_syntax() {
    local label="$1"
    local flag="$2"
    local in_file="$3"
    local out_file="$4"

    TEST_TOTAL=$((TEST_TOTAL + 1))

    if dcmconv "${flag}" "${in_file}" "${out_file}" >/dev/null 2>&1 \
            && [ -s "${out_file}" ]; then
        print_pass "Transfer Syntax: ${label} dcmconv ${flag} succeeded"
        TEST_PASSED=$((TEST_PASSED + 1))
        return 0
    fi

    print_fail "Transfer Syntax: ${label} dcmconv ${flag} failed"
    TEST_FAILED=$((TEST_FAILED + 1))
    return 1
}

# ── Helper: storescu acceptance against primary PACS ──
# Sends a single instance proposing exactly the transfer syntax under test via
# the matching storescu --propose-* option, so the SCP must negotiate that
# syntax rather than fall back to a default encoding. The propose flag is
# passed in by the caller (one of -xe / -xi / -xb).
assert_storescu_accepts() {
    local label="$1"
    local file="$2"
    local propose_flag="$3"

    TEST_TOTAL=$((TEST_TOTAL + 1))

    if storescu -aet "${MY_AE}" -aec "${PACS_AE}" "${propose_flag}" \
            "${PACS_HOST}" "${PACS_PORT}" "${file}" >/dev/null 2>&1; then
        print_pass "Transfer Syntax: ${label} storescu C-STORE accepted by ${PACS_AE}"
        TEST_PASSED=$((TEST_PASSED + 1))
        return 0
    fi

    print_fail "Transfer Syntax: ${label} storescu C-STORE rejected by ${PACS_AE}"
    TEST_FAILED=$((TEST_FAILED + 1))
    return 1
}

# ── Conversion + acceptance matrix ───────────────────
# (label, dcmconv flag, expected transfer syntax UID, storescu propose flag)
run_case() {
    local label="$1"
    local flag="$2"
    local expected_uid="$3"
    local propose_flag="$4"

    local out_file="${WORKDIR}/${label}.dcm"

    convert_transfer_syntax        "${label}" "${flag}" "${SOURCE_FILE}" "${out_file}" || return
    assert_transfer_syntax_uid     "${label}" "${out_file}" "${expected_uid}" || true
    assert_storescu_accepts        "${label}" "${out_file}" "${propose_flag}" || true
}

run_case "explicit-vr-le" "+te" "${TS_UID_EXPLICIT_LE}" "-xe"
run_case "implicit-vr-le" "+ti" "${TS_UID_IMPLICIT_LE}" "-xi"
run_case "explicit-vr-be" "+tb" "${TS_UID_EXPLICIT_BE}" "-xb"

# ── Summary ──────────────────────────────────────────
print_summary "Transfer Syntax"
[ "${TEST_FAILED}" -eq 0 ]
