#!/bin/bash
set -e

# Generate synthetic DICOM test data using dump2dcm.
# Usage: generate-test-data.sh [output_dir]
#
# Creates test patients with CT, MR, and CR modalities.
# Uses OID_ROOT env var for UID generation to avoid collision with clinical data.

OUTPUT_DIR="${1:-${TEST_DATA_DIR:-/dicom/testdata}}"
OID_ROOT="${OID_ROOT:-1.2.826.0.1.3680043.8.499}"

# Skip if test data already exists
if [ -d "${OUTPUT_DIR}" ] && [ "$(find "${OUTPUT_DIR}" -name '*.dcm' 2>/dev/null | wc -l)" -gt 0 ]; then
    echo "[generate-test-data] Test data already exists in ${OUTPUT_DIR}, skipping."
    exit 0
fi

mkdir -p "${OUTPUT_DIR}/ct" "${OUTPUT_DIR}/mr" "${OUTPUT_DIR}/cr"

echo "[generate-test-data] Generating synthetic DICOM files..."
echo "[generate-test-data] OID root: ${OID_ROOT}"
echo "[generate-test-data] Output: ${OUTPUT_DIR}"

TMPDIR=$(mktemp -d)
trap 'rm -rf "${TMPDIR}"' EXIT

# ── Helper: create a DICOM file from attributes ─────
# Args: output_file sop_class_uid sop_instance_uid patient_name patient_id
#       patient_sex study_uid study_date accession modality study_id study_desc
#       series_uid series_number series_desc instance_number
create_dicom() {
    local output_file="$1"
    local sop_class_uid="$2"
    local sop_instance_uid="$3"
    local patient_name="$4"
    local patient_id="$5"
    local patient_sex="$6"
    local study_uid="$7"
    local study_date="$8"
    local accession="$9"
    local modality="${10}"
    local study_id="${11}"
    local study_desc="${12}"
    local series_uid="${13}"
    local series_number="${14}"
    local series_desc="${15}"
    local instance_number="${16}"

    local dump_file="${TMPDIR}/$(basename "${output_file}" .dcm).txt"

    cat > "${dump_file}" << DUMP
# DICOM dump file - generated by generate-test-data.sh

# File Meta Information
(0002,0001) OB 00\\01
(0002,0002) UI =${sop_class_uid}
(0002,0003) UI [${sop_instance_uid}]
(0002,0010) UI =LittleEndianExplicit

# Patient Module
(0010,0010) PN [${patient_name}]
(0010,0020) LO [${patient_id}]
(0010,0040) CS [${patient_sex}]

# General Study Module
(0008,0020) DA [${study_date}]
(0008,0030) TM [120000]
(0008,0050) SH [${accession}]
(0008,1030) LO [${study_desc}]
(0020,000D) UI [${study_uid}]
(0020,0010) SH [${study_id}]

# General Series Module
(0008,0060) CS [${modality}]
(0008,103E) LO [${series_desc}]
(0020,000E) UI [${series_uid}]
(0020,0011) IS [${series_number}]

# General Image Module
(0020,0013) IS [${instance_number}]

# SOP Common Module
(0008,0016) UI =${sop_class_uid}
(0008,0018) UI [${sop_instance_uid}]
DUMP

    dump2dcm "${dump_file}" "${output_file}" 2>/dev/null
}

# ── Patient 1: DOE^JOHN - CT (5 slices) ─────────────
echo "[generate-test-data] Creating Patient 1: DOE^JOHN (CT, 5 instances)"

STUDY_UID="${OID_ROOT}.1.1"
SERIES_UID="${OID_ROOT}.1.1.1"

for i in $(seq 1 5); do
    SOP_UID="${OID_ROOT}.1.1.1.${i}"
    create_dicom \
        "${OUTPUT_DIR}/ct/ct_pat001_${i}.dcm" \
        "CTImageStorage" \
        "${SOP_UID}" \
        "DOE^JOHN" \
        "PAT001" \
        "M" \
        "${STUDY_UID}" \
        "20240115" \
        "ACC001" \
        "CT" \
        "STUDY001" \
        "CT Abdomen" \
        "${SERIES_UID}" \
        "1" \
        "Axial 5mm" \
        "${i}"
done

# ── Patient 2: SMITH^JANE - MR (2 series x 3) ──────
echo "[generate-test-data] Creating Patient 2: SMITH^JANE (MR, 6 instances)"

STUDY_UID="${OID_ROOT}.2.1"

# Series 1: T1
SERIES_UID="${OID_ROOT}.2.1.1"
for i in $(seq 1 3); do
    SOP_UID="${OID_ROOT}.2.1.1.${i}"
    create_dicom \
        "${OUTPUT_DIR}/mr/mr_pat002_s1_${i}.dcm" \
        "MRImageStorage" \
        "${SOP_UID}" \
        "SMITH^JANE" \
        "PAT002" \
        "F" \
        "${STUDY_UID}" \
        "20240220" \
        "ACC002" \
        "MR" \
        "STUDY002" \
        "MR Brain" \
        "${SERIES_UID}" \
        "1" \
        "T1 Axial" \
        "${i}"
done

# Series 2: T2
SERIES_UID="${OID_ROOT}.2.1.2"
for i in $(seq 1 3); do
    SOP_UID="${OID_ROOT}.2.1.2.${i}"
    create_dicom \
        "${OUTPUT_DIR}/mr/mr_pat002_s2_${i}.dcm" \
        "MRImageStorage" \
        "${SOP_UID}" \
        "SMITH^JANE" \
        "PAT002" \
        "F" \
        "${STUDY_UID}" \
        "20240220" \
        "ACC002" \
        "MR" \
        "STUDY002" \
        "MR Brain" \
        "${SERIES_UID}" \
        "2" \
        "T2 Axial" \
        "${i}"
done

# ── Patient 3: WANG^LEI - CR (2 images) ─────────────
echo "[generate-test-data] Creating Patient 3: WANG^LEI (CR, 2 instances)"

STUDY_UID="${OID_ROOT}.3.1"
SERIES_UID="${OID_ROOT}.3.1.1"

for i in $(seq 1 2); do
    SOP_UID="${OID_ROOT}.3.1.1.${i}"
    create_dicom \
        "${OUTPUT_DIR}/cr/cr_pat003_${i}.dcm" \
        "ComputedRadiographyImageStorage" \
        "${SOP_UID}" \
        "WANG^LEI" \
        "PAT003" \
        "M" \
        "${STUDY_UID}" \
        "20240310" \
        "ACC003" \
        "CR" \
        "STUDY003" \
        "Chest PA" \
        "${SERIES_UID}" \
        "1" \
        "Chest" \
        "${i}"
done

# ── Summary ──────────────────────────────────────────
TOTAL=$(find "${OUTPUT_DIR}" -name "*.dcm" | wc -l)
echo "[generate-test-data] Generation complete: ${TOTAL} DICOM files"
echo "[generate-test-data] CT: $(find "${OUTPUT_DIR}/ct" -name "*.dcm" | wc -l) files"
echo "[generate-test-data] MR: $(find "${OUTPUT_DIR}/mr" -name "*.dcm" | wc -l) files"
echo "[generate-test-data] CR: $(find "${OUTPUT_DIR}/cr" -name "*.dcm" | wc -l) files"
