#!/bin/bash
set -euo pipefail

# Generate Modality Worklist (.wl) files from the fixture manifest.
# Usage: generate-worklist.sh [output_dir]
#
# wlmscpfs serves worklist items from <data-files-path>/<CalledAETitle>/*.wl and
# REQUIRES a 'lockfile' in that directory (used for a read lock; if it is absent
# every C-FIND is refused with "Out of Resources"). Each .wl file is a DICOM
# object built with dump2dcm whose ScheduledProcedureStepSequence carries the
# modality, scheduled station AE, date/time, and description.
#
# Patient identity is taken from the shared fixture manifest, so a modality that
# fetches its worklist here sees the same patients/studies it will later C-STORE
# and that C-FIND/C-MOVE return from the Q/R PACS.

OUTPUT_DIR="${1:-${WLM_DATA_DIR:-/dicom/worklist}}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source the fixture manifest (single source of truth). Installed to
# /usr/local/bin in the image; alongside in scripts/ for host runs.
if [ -f "${SCRIPT_DIR}/fixture-manifest.sh" ]; then
    # shellcheck source=scripts/fixture-manifest.sh
    source "${SCRIPT_DIR}/fixture-manifest.sh"
elif [ -f /usr/local/bin/fixture-manifest.sh ]; then
    # shellcheck source=/usr/local/bin/fixture-manifest.sh
    source /usr/local/bin/fixture-manifest.sh
else
    echo "[generate-worklist] ERROR: fixture-manifest.sh not found" >&2
    exit 1
fi

# wlmscpfs looks for items under <dfp>/<CalledAETitle>/.
WL_DIR="${OUTPUT_DIR}/${MANIFEST_WLM_AE_TITLE}"
mkdir -p "${WL_DIR}"

# The lockfile is mandatory for wlmscpfs read locks; create it unconditionally.
touch "${WL_DIR}/lockfile"

# Skip regeneration if items already exist (the lockfile above is still ensured).
if [ "$(find "${WL_DIR}" -name '*.wl' 2>/dev/null | wc -l)" -gt 0 ]; then
    echo "[generate-worklist] Worklist already present in ${WL_DIR}, skipping."
    exit 0
fi

TMPD=$(mktemp -d)
trap 'rm -rf "${TMPD}"' EXIT

# Write one worklist item .wl via dump2dcm.
# Args: outfile patient_name patient_id patient_sex accession study_uid
#       modality scheduled_date sps_description
create_worklist_item() {
    local outfile="$1" pname="$2" pid="$3" psex="$4" accession="$5"
    local study_uid="$6" modality="$7" sdate="$8" sps_desc="$9"
    local dump="${TMPD}/$(basename "${outfile}" .wl).txt"

    cat > "${dump}" <<DUMP
# Modality Worklist item - generated by generate-worklist.sh
(0008,0005) CS [ISO_IR 100]
(0010,0010) PN [${pname}]
(0010,0020) LO [${pid}]
(0010,0030) DA [19700101]
(0010,0040) CS [${psex}]
(0008,0050) SH [${accession}]
(0020,000D) UI [${study_uid}]
(0032,1032) PN [${MANIFEST_WLM_PHYSICIAN}]
(0040,1001) SH [RP_${pid}]
(0040,0100) SQ
(fffe,e000)
(0008,0060) CS [${modality}]
(0040,0001) AE [${MANIFEST_WLM_STATION_AE}]
(0040,0002) DA [${sdate}]
(0040,0003) TM [${MANIFEST_WLM_START_TIME}]
(0040,0006) PN [${MANIFEST_WLM_PHYSICIAN}]
(0040,0007) LO [${sps_desc}]
(0040,0009) SH [SPS_${pid}]
(0040,0010) SH [${MANIFEST_WLM_STATION_NAME}]
(fffe,e00d)
(fffe,e0dd)
DUMP

    dump2dcm "${dump}" "${outfile}"
}

echo "[generate-worklist] Generating worklist items in ${WL_DIR}"

# Patient 1: CT
create_worklist_item "${WL_DIR}/wl_pat001_ct.wl" \
    "${MANIFEST_CT_PATIENT_NAME}" "${MANIFEST_CT_PATIENT_ID}" "${MANIFEST_CT_PATIENT_SEX}" \
    "${MANIFEST_CT_ACCESSION}" "${MANIFEST_CT_STUDY_UID}" "${MANIFEST_CT_MODALITY}" \
    "${MANIFEST_CT_STUDY_DATE}" "${MANIFEST_CT_STUDY_DESC}"

# Patient 2: MR
create_worklist_item "${WL_DIR}/wl_pat002_mr.wl" \
    "${MANIFEST_MR_PATIENT_NAME}" "${MANIFEST_MR_PATIENT_ID}" "${MANIFEST_MR_PATIENT_SEX}" \
    "${MANIFEST_MR_ACCESSION}" "${MANIFEST_MR_STUDY_UID}" "${MANIFEST_MR_MODALITY}" \
    "${MANIFEST_MR_STUDY_DATE}" "${MANIFEST_MR_STUDY_DESC}"

# Patient 3: CR
create_worklist_item "${WL_DIR}/wl_pat003_cr.wl" \
    "${MANIFEST_CR_PATIENT_NAME}" "${MANIFEST_CR_PATIENT_ID}" "${MANIFEST_CR_PATIENT_SEX}" \
    "${MANIFEST_CR_ACCESSION}" "${MANIFEST_CR_STUDY_UID}" "${MANIFEST_CR_MODALITY}" \
    "${MANIFEST_CR_STUDY_DATE}" "${MANIFEST_CR_STUDY_DESC}"

WL_COUNT=$(find "${WL_DIR}" -name '*.wl' | wc -l | tr -d ' ')
echo "[generate-worklist] Generated ${WL_COUNT} worklist items for AE ${MANIFEST_WLM_AE_TITLE}"
